### ISSUE TITLE
Connectors not getting aligned with blocks.

### ISSUE THREAD

**Issue by rajatsonibkn2002** [tudatn/react-svg-connector#5]
I am adding connectors with the blocks that get rendered automatically. But the problem is the connectors are coming in the center of the screen instead of getting aligned with the blocks.
![image](https://user-images.githubusercontent.com/55895192/206661449-91467c07-c75a-4451-9f59-01860bba788f.png)

**Comment by tudatn** [comment]
can you try to set position 'relative' for the wrapper (see example)? Or do you have a minimal code to reproduce the issue?

**Comment by rajatsonibkn2002** [comment]
![image](https://user-images.githubusercontent.com/55895192/207307712-d11f68a4-5a25-4b79-abd0-1570b6ff5d54.png)
I am now getting this issue, should I send you the code?

**Comment by tudatn** [comment]
a minimal code to reproduce the issue would be helpful

**Comment by rajatsonibkn2002** [comment]
`<ul>
            {
                blocks.map((item, index)=>{
                    return(
                        <>
                            <Connector
                                el1={document.getElementById("block"+(index-1))}
                                el2={document.getElementById("block"+(index))}
                                shape="narrow-s"
                                direction="b2t"
                                roundCorner={true}
                                endArrow={true}
                            />
                            <li id={"block"+index} key={index}>
                                <BlockRenderer type={item} key={index} />
                                <div>
                                {
                                    chains.map((item, chainIndex)=>{
                                        if(index===5){
                                        return(
                                            <Chain chainType={item} key={chainIndex} />
                                        )}
                                    })
                                }
                                </div>
                            </li>
                        </>
                    )
                })
            }
        </ul>`
        
        Here we have chains, which consist of blocks, and once the number of blocks reaches 5, we create a new block. Now we want to create a connector between every block, and between every parent chain and child chain.

**Comment by tudatn** [comment]
I'm not sure I can debug with the given code. But based on the screenshot, looks like to me that Connector is trying to connect wrapper elements `li` that have full width instead of `BlockRenderer`. I'd recommend to inspect these elements with the browser Inspector.
